services:
  c-spring-flow:
    build:
      context: ./
    ports:
      - 8080:8080
    networks:
      - mi-red
    environment:
      - URL_DATA_BASE:jdbc=postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - DATABASE_USERNAME=postgres.oskkthqxwfnabizsglth
      - DATABASE_PASSWORD=motopapis2013#
      - API_KEY=441CFF82-A48B-480E-A8A3-4CB5L66313B2
      - SECRET_KEY=1edc26ecef4736409a922490f6b243064681f407
networks:
  mi-red:
    driver: bridge